# 6. Conclusion

From the perspective of someone who has not read the book, the term co-occurrences and the dispersion plots allow to understand that *Invisible Women* is a feminist book which deals with a wide range of societal issues that affect our daily lives observed from a statistical lens through available data. The dispersion plots shows that *male* and *female* are often used in opposition or compared which indicates that the book insist on differences of treatment between men and women in societal matters. Moreover, the keyness by chapter is useful for understanding each chapter's topic of interest. Curiously, it is surprising that a machine learning model (Random Forest) classifies so well the pages in their respective part of the book, which shows that the vocabulary specificity allows a good recognition of the topics by the learner.

From the perspective of someone who has read *Invisible Women*, the analysis clarifies the understanding of the structure intended by the author. Indeed, each chapter is very well focused on the gender issue in one specific context and each part groups the contexts in specific domains (medical, technological, political...). Before the analysis, the evolution of the story seemed a bit disjointed in the sense that we jump from one context to the other without necessarily seeing a smooth transition. After the analysis, one realizes that the transitions between chapters are meant to explicitly represent a reality ruled by a male generic. Overall, the impression of the reader is that the sentiment emerged from the book is very negative, which is relatively well shown by the sentiment analysis. 

The person who has read the book confirms indeed the impressions of the others. Although, the one aspect that cannot be grasped by the text mining analysis is that they do not see the *data dump* happening in the book to illustrate the examples touched in the chapters. Regarding the sentiment emerging from the text, chapter 16 *It's Not the Disaster that Kills you* is the most negative chapter of the book and also the last one which confirms both impressions that the book does not spread hope regarding what the author is attempting to show, that women are invisible. 